### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by sebasurto** [joseluisgs/Programacion-AlumnosClase#1]
Hola. realizaba una tarea de diseño y encontré tu repositorio. Debía hallar algún code smell y refactorizar. 
Se halló lo siguiente. 
Lazy Class: Existe una clase para validar si se debe realizar un sorteo, esta clase es innecesaria y se puede refactorizar eliminándola y moviendo el método a otra .

Inappropriate Intimacy En la clase Alumno tenemos una clase para calcular nota, cuyo retorno no es un atributo de alumno y se usa en otra clase.  Longer Class 

En la clase clases tenemos una clase con demasiados métodos, muchos de estos dedicados al ordenamiento de un atributo de una lista de alumnos cuando, cuando estos pueden simplificarse o usar otra interface dedicada a ese funcionamiento que es más coherente a su naturaleza.

**Comment by joseluisgs** [comment]
Muchas gracias, pero este es un ejercicio para el alumnado oficial.
En cualquier caso lo que propones es correcto y te felicito por tu trabajo
